---
name: GPSD Container
description: GPSD Container for Homeassistant
slug: gpsd
url: http://github.com/mort666/ha-gpsd
image: "mort666/gpsd"
version: 1.0.6
arch:
  - amd64
startup: application
boot: auto
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_MODULE
map:
  - dev:rw
udev: true
full_access: true
ports:
  "2947/tcp": 2947
ports_description:
  "2947/tcp": GPSD streams
environment:
  HASS: "true"
ingress: true
ingress_port: 2947
