---
name: GPSD Container
description: GPSD Container for Homeassistant
slug: gpsd
url: http://github.com/mort666/ha-gpsd
image: "mort666/gpsd:{arch}-latest"
version: 1.0.2
arch:
  - amd64
startup: application
boot: auto
apparmor: false
ports:
  - "2947/tcp": 2947
ports_description:
  - "2947/tcp": GPSD streams
environment:
  HASS: "true"
ingress: true
ingress_port: 2947
