---
name: Portainer
description: Backdoor of Homeassistant
slug: gpsd
url: http://github.com/mort666/ha-gpsd
image: "portainer/agent"
version: 2.16.2
arch:
  - amd64
  - arm64
  - armv7
boot: auto
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_MODULE
udev: true
full_access: true
ports:
  "9001/tcp": 9001
ports_description:
  "9001/tcp": GPSD streams
environment:
  HASS: "true"
ingress: true
ingress_port: 9001
host_network: true
host_ipc: true
host_dbus: true
startup: system
