---
name: GPSD Container
description: GPSD Container for Homeassistant
slug: gpsd
url: http://github.com/mort666/ha-gpsd
image: "mort666/gpsd"
version: 1.0.3
arch:
  - amd64
startup: application
boot: auto
apparmor: false
privileged:
  - SYS_ADMIN
devices:
  - /dev/ttyACM0
  - /dev/ttyACM1
ports:
  "2947/tcp": 2947
ports_description:
  "2947/tcp": GPSD streams
environment:
  HASS: "true"
ingress: true
ingress_port: 2947
